create table public.group_members (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  site_id uuid null default gen_random_uuid (),
  user_id uuid null default gen_random_uuid (),
  constraint group_members_pkey primary key (id),
  constraint group_members_site_id_fkey foreign KEY (site_id) references sites (id),
  constraint group_members_user_id_fkey foreign KEY (user_id) references users (id)
) TABLESPACE pg_default;