create table public.user_attendances (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  employee_start_time time with time zone null,
  employee_end_time time with time zone null,
  user_id uuid null,
  total_hours character varying null,
  status text null,
  constraint user_attendances_pkey primary key (id),
  constraint user_attendances_user_id_fkey foreign KEY (user_id) references users (id)
) TABLESPACE pg_default;